@startuml

title Template Method Pattern

abstract class AbstractClass {

+ templateMethod()
# primitiveOperation1()
# primitiveOperation2()

}

class ConcreteClass {

# primitiveOperation1()
# primitiveOperation2()

}

AbstractClass <|-- ConcreteClass

@enduml