@startuml

hide footbox
autonumber
participant ConcreteSubject
participant ConcreteObserver1
participant ConcreteObserver2

ConcreteSubject <- ConcreteObserver1 : setState(subjectState : SubjectState) : void
activate ConcreteSubject
ConcreteSubject -> ConcreteSubject : notifyObservers() : void
activate ConcreteSubject
ConcreteSubject -> ConcreteObserver1 : update() : void
activate ConcreteObserver1
deactivate ConcreteSubject
ConcreteObserver1 -> ConcreteSubject : getState() : SubjectState
deactivate ConcreteObserver1
activate ConcreteSubject




@enduml