@startuml

hide footbox
autonumber

participant Client
participant ScoreRecord
participant DataSheetView

Client --> ScoreRecord : addScore(Score : int) : void

activate ScoreRecord
ScoreRecord --> DataSheetView : update() : void
deactivate ScoreRecord

activate DataSheetView
DataSheetView --> ScoreRecord : getScoreRecord() : List<Integer>
activate ScoreRecord
deactivate ScoreRecord
DataSheetView --> DataSheetView : displayScores(record : List<Integer>, viewCount : int) : void
activate DataSheetView
deactivate DataSheetView
deactivate DataSheetView

@enduml