@startuml
class Member
note left : 책을 대여하는 사람의 정보를 가진 클래스
class Rental
note top : Book과 Member의 연관 클래스로 회원이 책을 대여하는 행위에 대한 데이터를 취급
class Book
note right : 책정보를 갖는 클래스
interface PricePolicy
note right : 가격정책에 대한 인터페이스, Book이나 Member클래스에 따라 가격정책이 변함
class OrdinaryPricePolicy
class BookDiscountPricePolicy
class MemberDiscountPricePolicy

Member <- Rental
Rental -> Book
Rental --> PricePolicy
PricePolicy <|-- OrdinaryPricePolicy
PricePolicy <|-- BookDiscountPricePolicy
PricePolicy <|-- MemberDiscountPricePolicy
@enduml