@startuml

title : 데커레이터 패턴의 콜라보레이션

class Component {
    + operator()
}

class ConcreteComponent {
    + operator()
}

class Decorator {
    + operator()
}

note left : component.operation()

class ConcreteDecoratorA {
    + operator()
    - addedBehavior()
}

class ConcreteDecoratorB {
    + operator()
    - addedBehavior()
}

note left : super.operation(); \naddedBehavior();


Component --* Decorator : -component
Component <|.. ConcreteComponent
Component <|.. Decorator
Decorator <|-- ConcreteDecoratorA
Decorator <|-- ConcreteDecoratorB


@enduml