@startuml

abstract class Display {
    + draw() : void
}

class RoadDisplay {
    + draw() : void
}

class DisplayDecorator {
    + DisplayDecorator(decoratedDisplay : Display)
    + draw() : void
}

class LaneDecorator {
    + LaneDecorator(decoratedDisplay : Display)
    + draw() : void
    + drawLane() : void
}

class TrafficDecorator {
    + TrafficDecorator(decoratedDisplay : Display)
    + draw() : void
    + drawTraffic() : void
}

Display <|-- RoadDisplay
Display <|-- DisplayDecorator
Display --* DisplayDecorator : -decoratedDisplay
DisplayDecorator <|-- LaneDecorator
DisplayDecorator <|-- TrafficDecorator


@enduml