@startuml
[*] -up-> OFF
OFF -right-> ON : switch_on[power_exist] / turnon()
ON -left-> OFF : switch_off / turnoff()
ON -down-> WORKING : run / operate()
WORKING -UP-> ON : stop / suspend()
WORKING -left-> OFF : switch_off / turnoff()
@enduml